# Inspired from:
# https://gist.github.com/Broxzier/1ed980b8b3822d213e98042fc6a92040

# https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged
# https://stackoverflow.com/questions/55657835/is-there-a-way-to-push-changes-with-a-github-action
# https://github.com/stefanzweifel/git-auto-commit-action
# https://github.com/stefanzweifel/git-auto-commit-action
# https://stackoverflow.com/questions/70292203/is-it-possible-to-update-files-as-part-of-a-merge-via-github-actions-without-cre

# https://stackoverflow.com/questions/14348432/how-to-find-replace-and-increment-a-matched-number-with-sed-awk
# https://stackoverflow.com/questions/59757037/sed-command-doesnt-seem-to-process-quote-character-properly

name: Update package version on PR merge
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update_package_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # ref: ${{ github.head_ref }}
          # Fetch full depth, otherwise the last step overwrites the last commit parent, essentially removing the graph.
          fetch-depth: 0

      - name: Update pyproject version
        run: |
          echo prev_package_version=$(grep -E "version = \"[0-9+]\.[0-9+]\.[0-9]+\"" pyproject.toml | sed 's/version = //g') >> $GITHUB_ENV

          sed -ri 's/(version = )\"([0-9]+)\.([0-9]+)\.([0-9]+)\"/echo "\1\\\"\2.\3.$((\4+1))\\\""/ge' pyproject.toml

          echo next_package_version=$(grep -E "version = \"[0-9+]\.[0-9+]\.[0-9]+\"" pyproject.toml | sed 's/version = //g') >> $GITHUB_ENV

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "Update package version: ${{ env.prev_package_version }} -> ${{ env.next_package_version }}"
          file_pattern: 'pyproject.toml'
